import React from "react";
import FormikField from "../../../controls/FormikField";

export const AboutQuiz = () => {
  return (
    <React.Fragment>
      <small className="text-muted">Share this code with students</small>
      <FormikField
        name="code"
        className="form form-control mb-3"
        as="input"
        disabled
        placeholder="autogenerated code"
      />
      <small className="text-muted">
        Use descriptive tags e.g. "Amazon, Security, Specialty, Certification"
        will describe a quiz that was delivered at Amazon focused on security
        specialty certification
      </small>
      <FormikField
        name="tags"
        className="form form-control mb-3"
        as="input"
        placeholder="comma separated tags"
      />
      <small className="text-muted">Name of your quiz</small>
      <FormikField
        name="name"
        className="form form-control mb-3"
        as="input"
        placeholder="name"
      />
      <small className="text-muted">
        Short description in{" "}
        <a
          href="https://www.markdownguide.org/cheat-sheet/"
          rel="noopener noreferrer"
          target="_blank">
          markdown
        </a>{" "}
        or plain text
      </small>
      <FormikField
        name="description"
        className="form form-control mb-3"
        as="textarea"
        placeholder="description"
      />
      <small className="text-muted">
        Precise instructions in markdown or plain text
      </small>
      <FormikField
        name="instructions"
        className="form form-control mb-3"
        as="textarea"
        placeholder="instructions"
      />
    </React.Fragment>
  );
};
